### PR TITLE
Add gpa function to generators.jl

### PR DESCRIPTION
**Pull request by eikmeier**

### CODE REVIEW

**Comment by dgleich** [comment]
We'll need some test-cases for this -- see the testing routines for pa_graph in the test folder.

**Comment by dgleich** [comment]
Quick Q -- do you know what removed all the white-space from the end of lines in src/generators.jl?

**Comment by nassarhuda** [comment]
It could be the editor Nicole is using...

**Comment by dgleich** [comment]
It was atom .. they have some new setting that does this. How annoying!

**Pull request merged**
