### PR TITLE
use T instead of Float64 for values

### PR DESCRIPTION
**Pull request by Wikunia**
Use the correct type for value arrays.

### CODE REVIEW

**Comment by dgleich** [comment]
We should probably add some tests for anything other than Float64... This could cause a problem if the weights are integers, for example...

**Comment by Wikunia** [comment]
Actually it seems like the test case for `bipartite_matching` uses only integer weights.
https://github.com/nassarhuda/MatrixNetworks.jl/blob/master/test/bipartite_matching_test.jl#L6

I can add further tests if you wish. I tried it in my project with boolean.

**Comment by dgleich** [comment]
Which, I think, is why this allocates float64s, as this is a real valued
computation even for integer weights.

**Comment by Wikunia** [comment]
Just saw that the matching setup needs to be dependent on `T` as well then:
https://github.com/nassarhuda/MatrixNetworks.jl/blob/42d8d841e32f1eb90027a1baa747de874301f636/src/bipartite_matching.jl#L40

`ai` holds only the information of the values or a `0` but it is divided by something in `bipartite_matching_primal_dual` which would make it a float again. 
I see. Then I think: https://github.com/nassarhuda/MatrixNetworks.jl/blob/42d8d841e32f1eb90027a1baa747de874301f636/src/bipartite_matching.jl#L144 
should be `= 0.0` but not sure whether that's important. 

I'm mostly interested in bipartite matching without weights (all 1) and thinking about whether there is a significant gain in performance if that would be a special function.

**Comment by dgleich** [comment]
There is a faster way to do this using integer weights. Usually max-flow min-cut algs are the way to go there. 

I'm reluctant to make changes to this code that could render it incorrect without deeper testing routines. So to make your change, we'd need that testing evaluation.

**Comment by Wikunia** [comment]
Okay thanks for the suggestion. I'll have a look into int and create a different PR then.
Will make sure to add test sets then ;)

**Pull request closed without merging**
