### PR TITLE
Misc tests

### PR DESCRIPTION
**Pull request by kshyatt**
Trying to get you that pretty green 90% badge :)

### CODE REVIEW

**Comment by dgleich** [comment]
Ooh! This looks great! Thanks so much. @nassarhuda  do you want to take a look too?

**Comment by kshyatt** [comment]
Sorry, I got a little carried away...

**Comment by nassarhuda** [comment]
hah I was *just* looking at the travis errors

**Comment by kshyatt** [comment]
Sunday morning bump :)

**Comment by nassarhuda** [comment]
Thank you @kshyatt for all the tests :)

**Pull request merged**
