### PR TITLE
use github-ci instead of travis

### PR DESCRIPTION
**Pull request by Wikunia**
You might need to add `DOCUMENTER_KEY` to your secrets for the documentation if you haven't already.

The details for that can be found here:
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh (it's the same procedure for Github actions)

### CODE REVIEW

**Comment by nassarhuda** [comment]
Just to clarify, is this PR still waiting to be merged? (just because I see that some checks haven't passed).

**Comment by Wikunia** [comment]
Hey @nassarhuda , 
this currently only fails as I don't have access to add the documenter key to your GitHub secrets :wink:

**Comment by dgleich** [comment]
Since we aren't using documentation, shouldn't we just take that entire
section out?

**Comment by Wikunia** [comment]
Good point @dgleich didn't realize that you don't have docs for the project. 
I've updated the PR accordingly.

**Comment by nassarhuda** [comment]
Thanks @Wikunia for the PRs! -- sorry I didn't notice what the one check that didn't pass was.

**Pull request merged**
